# app/config.py

DISCOVERY_RANGE = 10.0
BROADCAST_INTERVAL = 3
BASE_PORT = 5000
MAX_ATTEMPTS = 3
NUM_NODES = 5
POSITIONS_FILE = "positions.json"
DELAY = 1
NUM_GROUND_STATIONS = 2
GROUND_STATION_POSITIONS_FILE = "ground_stations.json"
